- name: Deploy Next.js App
  hosts: lekkoatletawka
  become: yes
  vars:
    app_name: lekkoatletawka_web
    app_repo: https://github.com/alicenoknow/lekko-web.git
    app_path: /var/www/{{ app_name }}

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Clone Next.js repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        version: main
        force: yes

    - name: Install dependencies
      npm:
        path: "{{ app_path }}"
        production: yes

    - name: Build the Next.js app
      shell: npm run build
      args:
        chdir: "{{ app_path }}"
      environment:
        NODE_ENV: production

    # - name: Start app using PM2
    #   shell: |
    #     pm2 delete {{ app_name }} || true
    #     pm2 start npm --name "{{ app_name }}" -- start
    #     pm2 save
    #   args:
    #     chdir: "{{ app_path }}"