---

- name: Install Node.js and npm on Debian/Ubuntu
  hosts: lekkoatletawka
  become: yes

  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install npm
      apt:
        name: npm
        state: present

    - name: Ensure PM2 is installed
      npm:
        name: pm2
        global: yes
        state: present
      environment:
        NODE_ENV: production

    # Verify installation
    - name: Verify Node.js installation
      command: node --version
      register: node_version_output
      changed_when: false

    - name: Verify npm installation
      command: npm --version
      register: npm_version_output
      changed_when: false

    - name: Verify PM2 installation
      command: pm2 --version
      register: pm2_version_output
      changed_when: false

    # Display installation information
    - name: Show Node.js and npm versions
      debug:
        msg: 
          - "Node.js version: {{ node_version_output.stdout }}"
          - "npm version: {{ npm_version_output.stdout }}"
          - "PM2 version: {{ pm2_version_output.stdout }}"